### ISSUE TITLE
TODO for 4.0

### ISSUE THREAD

**Issue by blink1073** [blink1073/oct2py#103]
- [x] Dynamic classes (#80)
- [x] Another pass at logical type handling (will have to increase minimum Scipy version) (#94)
- [ ] Fix interrupt behavior on Windows (#100)
- [x] Graceful import failure (#102)
- [ ] Clean up code evaluation (#105)
- [x] Look into function pointer handling - not possible - see http://savannah.gnu.org/bugs/?43215

**Comment by blink1073** [comment]
Notes for steam handling:

- `octave.ones(3)` should absorb the answer and give it back as a value in the repl
- `y = octave.ones(3)` should not print anything by default
- `octave.disp('hi')` should print to stdout
- `y = octave.disp('hi')` should not print anything by default
- `octave.eval('for i=1:3;disp("hi");sleep(1);end')` should print incremental output

- Solution: verbose should control whether we add a semicolon to the line.  Adding an extra semicolon does no harm.

**Comment by blink1073** [comment]
Moving checklist to #108.
